INSERT INTO Locations (Name) VALUES ('Faculty of Computing');
INSERT INTO Locations (Name) VALUES ('Faculty of Agriculture');
INSERT INTO Locations (Name) VALUES ('Faculty of Arts');
INSERT INTO Locations (Name) VALUES ('Faculty of Science');
INSERT INTO Locations (Name) VALUES ('Faculty of Islamiyat');
INSERT INTO Locations (Name) VALUES ('Institute of Businesss Management');
INSERT INTO Locations (Name) VALUES ('Faculty of Zoology');
INSERT INTO Locations (Name) VALUES ('Faculty of DVM');
INSERT INTO Locations (Name) VALUES ('Faculty of Engineering');
INSERT INTO Locations (Name) VALUES ('Faculty of Education');
INSERT INTO Locations (Name) VALUES ('Lecture Halls');
INSERT INTO Locations (Name) VALUES ('Administration Building');
INSERT INTO Locations (Name) VALUES ('Registrars Office');
INSERT INTO Locations (Name) VALUES ('Financial Aid Office');
INSERT INTO Locations (Name) VALUES ('Admissions Office');
INSERT INTO Locations (Name) VALUES ('Student Affairs Office');
INSERT INTO Locations (Name) VALUES ('Human Resources');
INSERT INTO Locations (Name) VALUES ('Student Center');
INSERT INTO Locations (Name) VALUES ('Sports Complex');
INSERT INTO Locations (Name) VALUES ('Gymnasium');
INSERT INTO Locations (Name) VALUES ('Swimming Pool');
INSERT INTO Locations (Name) VALUES ('Tennis Courts');
INSERT INTO Locations (Name) VALUES ('Football Field');
INSERT INTO Locations (Name) VALUES ('Main Quad');
INSERT INTO Locations (Name) VALUES ('Gardens and Parks');
INSERT INTO Locations (Name) VALUES ('Parking Lots');
INSERT INTO Locations (Name) VALUES ('Bus Stops');
INSERT INTO Locations (Name) VALUES ('Health Center');
INSERT INTO Locations (Name) VALUES ('Counseling Center');
INSERT INTO Locations (Name) VALUES ('IT Help Desk');
INSERT INTO Locations (Name) VALUES ('Auditorium');
INSERT INTO Locations (Name) VALUES ('Exhibition Hall');
